# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longtude', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
