# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationofuser',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationofuser',
            name='longtude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
